export const menuData = {
  signature: [
    {
      id: "sig-001",
      name: "Wedang Jiwa Milk Tea",
      shortDescription: "Jahe merah, black tea, fresh milk & gula aren",
      fullDescription:
        "Perpaduan jahe merah pilihan dengan black tea blend yang robust dan susu segar yang lembut, berpadu harmonis dalam kehangatan yang menenangkan jiwa.",
      price: { regular: 24000, large: 30000 },
      image: "/images/menu/wedang-jiwa-milk-tea.jpg",
      ingredients: ["Jahe merah", "Black tea blend", "Fresh milk", "Gula aren"],
      benefits: ["Menghangatkan", "Anti-mual", "Sirkulasi darah", "Antibakteri"],
      mood: ["Relaxed & Warm", "Low Energy Recovery", "After Work"],
      category: "signature",
    },
    {
      id: "sig-002",
      name: "Aruna Matcha Beras Kencur",
      shortDescription: "Japanese matcha, beras kencur, fresh milk & madu",
      fullDescription:
        "Matcha Jepang premium bertemu beras kencur tradisional dalam harmoni yang unik — fokus tajam dengan pencernaan sehat dalam satu gelas.",
      price: { regular: 25000, large: 31000 },
      image: "/images/menu/aruna-matcha-beras-kencur.jpg",
      ingredients: ["Japanese matcha", "Beras kencur powder", "Fresh milk", "Madu"],
      benefits: ["Fokus & Konsentrasi", "Pencernaan sehat", "Antioksidan", "Stamina"],
      mood: ["Focus & Study", "Digestive Discomfort", "Morning Boost"],
      category: "signature",
    },
    {
      id: "sig-003",
      name: "Kencana Ginger Lemon Tea",
      shortDescription: "Jahe segar, lemon, green tea & madu",
      fullDescription:
        "Kesegaran lemon bertemu kehangatan jahe segar dalam balutan green tea — perisai imunitas alami yang menyegarkan sepanjang hari.",
      price: { regular: 22000, large: 28000 },
      image: "/images/menu/kencana-ginger-lemon-tea.jpg",
      ingredients: ["Jahe segar", "Lemon segar", "Green tea", "Madu"],
      benefits: ["Imunitas", "Detoks ringan", "Anti-inflamasi", "Menyegarkan"],
      mood: ["Immune Support", "Need Refreshing", "Detox Light"],
      category: "signature",
    },
  ],

  classic: [
    {
      id: "cls-001",
      name: "Brown Sugar Asam Milk Tea",
      shortDescription: "Asam jawa, brown sugar, black tea & fresh milk",
      fullDescription:
        "Asam jawa yang kaya bertemu brown sugar syrup karamel dalam black tea blend susu — minuman harian yang mendukung pencernaan dan menjaga mood tetap positif.",
      price: { regular: 25000, large: 31000 },
      image: "/images/menu/brown-sugar-asam-milk-tea.jpg",
      ingredients: ["Asam jawa", "Brown sugar syrup", "Black tea", "Fresh milk"],
      benefits: ["Pencernaan", "Energi stabil", "Mood booster", "Antioksidan"],
      mood: ["Balanced Energy", "Mood Booster", "Everyday Drink"],
      category: "classic",
    },
    {
      id: "cls-002",
      name: "Telang Sekar Blue Milk Tea",
      shortDescription: "Bunga telang, lemon, fresh milk & gula aren",
      fullDescription:
        "Bunga telang biru alami yang memukau berpadu dengan kesegaran lemon dan kelembutan susu — cantik di gelas, kaya antioksidan di dalam tubuh.",
      price: { regular: 22000, large: 28000 },
      image: "/images/menu/telang-sekar-blue-milk-tea.jpg",
      ingredients: ["Bunga telang", "Lemon", "Fresh milk", "Gula aren"],
      benefits: ["Antioksidan", "Relaksasi", "Kesehatan mata", "Detoks ringan"],
      mood: ["Relaxation", "Light Detox", "Aesthetic Vibe"],
      category: "classic",
    },
    {
      id: "cls-003",
      name: "JAMOO Black Milk Tea",
      shortDescription: "Premium black tea, fresh milk, gula aren & kayu manis",
      fullDescription:
        "Black tea premium dengan sentuhan kayu manis dan gula aren — pintu masuk yang familiar ke dunia JAMOO, sempurna untuk setiap hari.",
      price: { regular: 22000, large: 28000 },
      image: "/images/menu/jamoo-black-milk-tea.jpg",
      ingredients: ["Premium black tea blend", "Fresh milk", "Gula aren", "Kayu manis"],
      benefits: ["Fokus", "Antioksidan", "Kesehatan jantung", "Energi"],
      mood: ["Focus & Sustained Energy", "Everyday"],
      category: "classic",
    },
    {
      id: "cls-004",
      name: "Rosella Hibiscus Cooler",
      shortDescription: "Rosella, hibiscus, lemon & gula aren — sparkling",
      fullDescription:
        "Rosella dan hibiscus berpadu dalam minuman sparkling berwarna merah alami yang memukau — mood-lifting, kaya vitamin C, menyegarkan total.",
      price: { regular: 23000, large: 29000 },
      image: "/images/menu/rosella-hibiscus-cooler.jpg",
      ingredients: ["Rosella powder", "Hibiscus extract powder", "Lemon powder", "Gula aren powder"],
      benefits: ["Tekanan darah", "Vitamin C", "Mood lifting", "Antioksidan"],
      mood: ["Mood Lift", "Blood Pressure Support", "Refreshing"],
      category: "classic",
    },
    {
      id: "cls-005",
      name: "Kayu Manis Oat Latte",
      shortDescription: "Kayu manis, oat milk, gula aren, jahe & vanilla",
      fullDescription:
        "Kehangatan kayu manis bertemu creamy oat milk dalam latte yang menstabilkan gula darah — pilihan cerdas untuk kamu yang diet-conscious.",
      price: { regular: 24000, large: 30000 },
      image: "/images/menu/kayu-manis-oat-latte.jpg",
      ingredients: ["Kayu manis powder", "Oat milk powder", "Gula aren powder", "Jahe powder", "Vanilla powder"],
      benefits: ["Gula darah stabil", "Anti-craving", "Hangat & creamy", "Diet-friendly"],
      mood: ["Blood Sugar Balance", "Cozy Morning", "Anti-Cravings"],
      category: "classic",
    },
    {
      id: "cls-006",
      name: "Temu Ireng Dark Stamina",
      shortDescription: "Temu ireng, jahe emprit, madu, lada hitam & susu",
      fullDescription:
        "Formula stamina dari temu ireng dan jahe emprit yang intensif — dirancang untuk recovery aktif dan performa optimal post-workout.",
      price: { regular: 25000, large: 31000 },
      image: "/images/menu/temu-ireng-dark-stamina.jpg",
      ingredients: ["Temu ireng powder", "Jahe emprit powder", "Madu powder", "Lada hitam powder", "Milk powder"],
      benefits: ["Stamina", "Anti-inflamasi", "Sirkulasi darah", "Recovery"],
      mood: ["Stamina Boost", "Active Recovery", "Post-Workout"],
      category: "classic",
    },
    {
      id: "cls-007",
      name: "Serai Lemongrass Mint Fizz",
      shortDescription: "Serai, mint, lemon & gula aren — sparkling",
      fullDescription:
        "Serai segar bertemu mint dan lemon dalam minuman sparkling yang menyegarkan total — cocok untuk siang hari yang panas dan butuh fokus.",
      price: { regular: 23000, large: 29000 },
      image: "/images/menu/serai-lemongrass-mint-fizz.jpg",
      ingredients: ["Serai powder", "Mint powder", "Lemon powder", "Gula aren powder"],
      benefits: ["Menyegarkan", "Anti-anxietas", "Pencernaan", "Fokus"],
      mood: ["Refreshing", "Focus", "Summer Vibe"],
      category: "classic",
    },
  ],

  heritage: [
    {
      id: "her-001",
      name: "Bandrek Sunda Milk Latte",
      shortDescription: "Jahe, gula merah, kayu manis, cengkeh & fresh milk",
      fullDescription:
        "Bandrek khas Sunda yang hangat dan aromatik, dipadukan dengan fresh milk menjadi latte modern — meningkatkan stamina dan menghangatkan di hari hujan.",
      price: { regular: 23000, large: 29000 },
      image: "/images/menu/bandrek-sunda-milk-latte.jpg",
      ingredients: ["Jahe", "Gula merah", "Kayu manis", "Cengkeh", "Daun pandan", "Fresh milk"],
      benefits: ["Menghangatkan", "Stamina", "Anti-inflamasi", "Masuk angin"],
      mood: ["Warming", "Stamina Boost", "Rainy Day"],
      asalDaerah: "Sunda, Jawa Barat",
      category: "heritage",
    },
    {
      id: "her-002",
      name: "Bajigur Aren Oat Latte",
      shortDescription: "Gula aren, santan, jahe, oat milk & kayu manis",
      fullDescription:
        "Bajigur tradisional Priangan yang nyaman dan comforting, dimodernisasi dengan oat milk — menjaga pencernaan dan memberikan kehangatan total.",
      price: { regular: 24000, large: 30000 },
      image: "/images/menu/bajigur-aren-oat-latte.jpg",
      ingredients: ["Gula aren", "Santan ringan", "Jahe", "Oat milk", "Kayu manis"],
      benefits: ["Kesehatan tulang", "Pencernaan", "Gula darah stabil", "Mineral alami"],
      mood: ["Cozy & Comforting", "Digestive Support", "Relaxed"],
      asalDaerah: "Priangan, Jawa Barat",
      category: "heritage",
    },
    {
      id: "her-003",
      name: "Wedang Uwuh Sparkling",
      shortDescription: "Jahe, serai, kayu secang, pandan & soda",
      fullDescription:
        "Wedang Uwuh legendaris Yogyakarta kini hadir dalam versi sparkling — warna merah kayu secang yang memukau dengan sensasi bubble yang unik.",
      price: { regular: 23000, large: 29000 },
      image: "/images/menu/wedang-uwuh-sparkling.jpg",
      ingredients: ["Jahe", "Serai", "Kayu secang", "Pandan wangi", "Kayu manis", "Soda"],
      benefits: ["Antioksidan", "Menghangatkan", "Anti-inflamasi", "Imunitas"],
      mood: ["Energetic", "Immune Boost", "Unique Experience"],
      asalDaerah: "Yogyakarta",
      category: "heritage",
    },
    {
      id: "her-004",
      name: "Bir Pletok Betawi Tonic",
      shortDescription: "Jahe, serai, kayu secang, pandan & tonic water",
      fullDescription:
        "Bir Pletok khas Betawi yang ikonik — zero alkohol, berwarna merah alami dari kayu secang, menyegarkan dengan tonic water dan kaya manfaat herbal.",
      price: { regular: 24000, large: 30000 },
      image: "/images/menu/bir-pletok-betawi-tonic.jpg",
      ingredients: ["Jahe", "Serai", "Pandan wangi", "Kayu secang", "Tonic water"],
      benefits: ["Zero alkohol", "Stamina alami", "Relaksasi", "Anti-inflamasi"],
      mood: ["Refreshing", "Focus", "Non-Caffeine Energy"],
      asalDaerah: "Betawi, Jakarta",
      category: "heritage",
    },
    {
      id: "her-005",
      name: "Kunyit Asam Tamarind Cooler",
      shortDescription: "Kunyit segar, asam jawa, gula aren, lemon & jahe",
      fullDescription:
        "Kunyit asam klasik Jawa yang melegenda — detoks hati dengan kurkumin kunyit dan asam jawa, cocok untuk post-workout dan keseimbangan hormon.",
      price: { regular: 22000, large: 28000 },
      image: "/images/menu/kunyit-asam-tamarind-cooler.jpg",
      ingredients: ["Kunyit segar", "Asam jawa", "Gula aren", "Lemon", "Jahe"],
      benefits: ["Detoks hati", "Nyeri menstruasi", "Anti-inflamasi", "Pencernaan"],
      mood: ["Detox", "Hormone Balance", "Post-Workout"],
      asalDaerah: "Jawa Tengah / Nasional",
      category: "heritage",
    },
    {
      id: "her-006",
      name: "Temulawak Citrus Fizz",
      shortDescription: "Temulawak, jeruk nipis, madu, soda & jahe",
      fullDescription:
        "Temulawak khas Jawa yang kaya xanthorrhizol berpadu citrus segar dalam minuman fizzy — menjaga liver, meningkatkan nafsu makan, dan menyegarkan setelah makan.",
      price: { regular: 23000, large: 29000 },
      image: "/images/menu/temulawak-citrus-fizz.jpg",
      ingredients: ["Temulawak", "Jeruk nipis", "Madu", "Soda ringan", "Jahe"],
      benefits: ["Kesehatan liver", "Nafsu makan", "Anti-inflamasi", "Pencernaan"],
      mood: ["Liver Health", "Energetic", "After Meal"],
      asalDaerah: "Jawa, Nasional",
      category: "heritage",
    },
    {
      id: "her-007",
      name: "Sekoteng Moderne",
      shortDescription: "Kuah jahe kental, kacang hijau, santan & gula aren",
      fullDescription:
        "Sekoteng tradisional yang dimodernisasi — jahe kental melancarkan aliran darah ke otak, kacang hijau kaya protein dan serat, mengenyangkan dan menghangatkan total.",
      price: { regular: 24000, large: 30000 },
      image: "/images/menu/sekoteng-moderne.jpg",
      ingredients: ["Kuah jahe kental", "Kacang hijau", "Santan ringan", "Gula aren", "Kayu manis"],
      benefits: ["Redakan sakit kepala", "Protein & serat", "Mengenyangkan", "Menghangatkan"],
      mood: ["Full Warmth", "Headache Relief", "Winter Mode"],
      asalDaerah: "Nasional",
      category: "heritage",
    },
  ],
}
